export enum Languages {
  English = "en",
  Spanish = "es",
  Portuguese = "pt",
  Hindi = "hi",
  Arabic = "ar",
  Bengali = "bn",
  Russian = "ru",
  Japanese = "ja",
  German = "de",
  French = "fr",
  Turkish = "tr",
  Korean = "ko",
  Italian = "it",
  Vietnamese = "vi",
  Urdu = "ur",
  Indonesian = "id",
  Persian = "fa",
  Polish = "pl",
  Dutch = "nl",
  Chinese = "zh",
}
